### ISSUE TITLE
选中弹框的显示位置

### ISSUE THREAD

**Issue by ShirleyLuoppx** [D10NGYANG/DL10SideBar#1]
请问，可以设置选中弹框的显示位置吗，好像是默认的，但是放在横屏机器上面位置就不太适合了。望回复

**Comment by D10NGYANG** [comment]
自己去定制这个文件就可以了，dlsidebar/src/main/java/com/dlong/rep/dlsidebar/DLTextDialog.java
这个项目暂时没空去维护
